### ISSUE TITLE
INFOGRAFÍA 

### ISSUE THREAD

**Issue by Antonia2410** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Antonia2410#1]
[LIBRERÍA_ANTONIA-SANTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Antonia2410/files/14540340/LIBRERIA_ANTONIA-SANTOS.pdf)

**Comment by AricelCastro** [comment]
Mi equipo le da una calificación de 19.5 /20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
